In [12]:

# Esto te dirá en qué carpeta está el notebook realmente
print(f"Directorio actual: {os.getcwd()}")

# Esto te dirá qué hay una carpeta arriba
print(f"Contenido de '..': {os.listdir('..')}")

Directorio actual: c:\Users\julia\c2526-R5\src\models\prediccion_propagacion
Contenido de '..': ['common', 'modelos_alertas', 'prediccion_propagacion', 'prediccion_retrasos', 'seleccion_variables.md']

In [13]:
import os
import sys

# 1. Calculamos la ruta de la carpeta 'src'
# Estamos en: src/models/prediccion_propagacion
# Subimos un nivel (..) -> src/models
# Subimos otro nivel (..) -> src
ruta_src = os.path.abspath(os.path.join(os.getcwd(), '..', '..'))

# 2. La añadimos al path si no está ya
if ruta_src not in sys.path:
    sys.path.insert(0, ruta_src)

# 3. Ahora el import funcionará buscando dentro de 'src'
from common.minio_client import download_df_parquet

print("✅ Importación realizada con éxito desde:", ruta_src)

✅ Importación realizada con éxito desde: c:\Users\julia\c2526-R5\src

In [16]:

access_key = os.getenv("MINIO_ACCESS_KEY")
secret_key = os.getenv("MINIO_SECRET_KEY")

ruta_archivo = "grupo5/final/year=2025/month=01/dataset_final.parquet"
df = download_df_parquet(access_key, secret_key, ruta_archivo)

In [17]:
df

,date,match_key,stop_id,route_id,direction,delay_seconds,lagged_delay_1,lagged_delay_2,route_rolling_delay,actual_headway_seconds,...,afecta_durante,afecta_despues,category,num_updates,timestamp_start,seconds_since_last_alert,is_alert_just_published,seconds_to_next_alert,alert_in_next_15m,alert_in_next_30m
0,2025-01-01,137350_D..S07R,B12S,D,S,-30.0,NaN,NaN,NaN,NaN,...,0,0,NaN,0.0,NaT,NaN,0,9840.0,0,0
1,2025-01-01,287600_3..N01R,254N,NaN,N,NaN,NaN,NaN,NaN,NaN,...,0,0,NaN,0.0,NaT,NaN,0,NaN,0,0
2,2025-01-01,284850_1..S03R,123S,NaN,S,NaN,NaN,NaN,NaN,NaN,...,0,0,NaN,0.0,NaT,NaN,0,NaN,0,0
3,2025-01-01,141700_J..N40R,J30N,J,N,-58.0,NaN,NaN,92.000000,NaN,...,0,0,NaN,0.0,NaT,NaN,0,1018.0,0,1
4,2025-01-01,140200_J..N40R,J20N,J,N,92.0,NaN,NaN,NaN,NaN,...,0,0,NaN,0.0,NaT,NaN,0,1018.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6401882,2025-01-31,137800_F..S,F15S,NaN,S,NaN,NaN,NaN,NaN,800.0,...,0,0,NaN,0.0,NaT,NaN,0,NaN,0,0
6401883,2025-01-31,143100_E..N05R,A30N,E,N,-5.0,-5.0,10.0,253.199997,125.0,...,0,0,Other,0.0,2025-01-31 20:38:00,12115.0,0,NaN,0,0
6401884,2025-01-31,134450_2..N01R,208N,2,N,596.0,614.0,606.0,454.799988,844.0,...,0,0,Delay,0.0,2025-01-31 21:40:00,8396.0,0,NaN,0,0
6401885,2025-01-31,135750_4..N,402N,NaN,N,NaN,NaN,NaN,NaN,554.0,...,0,0,NaN,0.0,NaT,NaN,0,NaN,0,0
6401886,2025-01-31,141950_G..N15X015,G22N,G,N,448.0,440.0,NaN,144.000000,1198.0,...,0,0,Delay,0.0,2025-01-31 22:56:00,3838.0,0,NaN,0,0

In [18]:
df.columns

Index(['date', 'match_key', 'stop_id', 'route_id', 'direction',
       'delay_seconds', 'lagged_delay_1', 'lagged_delay_2',
       'route_rolling_delay', 'actual_headway_seconds', 'is_unscheduled',
       'hour_sin', 'hour_cos', 'dow', 'is_weekend', 'target_delay_10m',
       'target_delay_20m', 'target_delay_30m', 'target_delay_45m',
       'target_delay_60m', 'station_delay_10m', 'station_delay_20m',
       'station_delay_30m', 'target_delay_end', 'delta_delay_10m',
       'delta_delay_20m', 'delta_delay_30m', 'delta_delay_45m',
       'delta_delay_60m', 'delta_delay_end', 'stops_to_end', 'merge_time',
       'scheduled_time_to_end', 'temp_extreme', 'n_eventos_afectando',
       'tipo_referente', 'afecta_previo', 'afecta_durante', 'afecta_despues',
       'category', 'num_updates', 'timestamp_start',
       'seconds_since_last_alert', 'is_alert_just_published',
       'seconds_to_next_alert', 'alert_in_next_15m', 'alert_in_next_30m'],
      dtype='object')

In [24]:
import pandas as pd
df2 = pd.read_csv("MTA_Subway_Stations.xls")

In [37]:
len(df['stop_id'].str[:3].unique())

523

In [38]:
len(df2['GTFS Stop ID'].str[:3].unique())

496

In [25]:
df2

,GTFS Stop ID,Station ID,Complex ID,Division,Line,Stop Name,Borough,CBD,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude,North Direction Label,South Direction Label,ADA,ADA Northbound,ADA Southbound,ADA Notes,Georeference
0,127,317,611,IRT,Broadway - 7Av,Times Sq-42 St,M,True,1 2 3,Subway,40.755290,-73.987495,Uptown,Downtown,1,1,1,NaN,POINT (-73.987495 40.75529)
1,S17,515,515,SIR,Staten Island,Annadale,SI,False,SIR,Open Cut,40.540460,-74.178217,Ferry,South Shore,0,0,0,NaN,POINT (-74.178217 40.54046)
2,S01,139,627,BMT,Franklin Shuttle,Franklin Av,Bk,False,S,Elevated,40.680596,-73.955827,Last Stop,Prospect Park,1,1,1,NaN,POINT (-73.955827 40.680596)
3,254,349,349,IRT,Eastern Pky,Junius St,Bk,False,3,Elevated,40.663515,-73.902447,Manhattan,New Lots,0,0,0,NaN,POINT (-73.902447 40.663515)
4,M01,108,108,BMT,Myrtle Av,Middle Village-Metropolitan Av,Q,False,M,Elevated,40.711396,-73.889601,Inbound,Last Stop,1,1,1,NaN,POINT (-73.889601 40.711396)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,B06,222,222,IND,63rd St,Roosevelt Island,M,False,M,Subway,40.759145,-73.953260,Queens,Downtown,1,1,1,NaN,POINT (-73.95326 40.759145)
492,J15,83,83,BMT,Jamaica,Woodhaven Blvd,Q,False,J Z,Elevated,40.693879,-73.851576,Jamaica,Manhattan,1,1,1,NaN,POINT (-73.851576 40.693879)
493,S18,514,514,SIR,Staten Island,Eltingville,SI,False,SIR,Embankment,40.544601,-74.164570,Ferry,South Shore,0,0,0,NaN,POINT (-74.16457 40.544601)
494,F14,232,232,IND,6th Av - Culver,2 Av,M,True,F,Subway,40.723402,-73.989938,Uptown,Downtown,0,0,0,NaN,POINT (-73.989938 40.723402)
495,253,348,348,IRT,Eastern Pky,Rockaway Av,Bk,False,3,Elevated,40.662549,-73.908946,Manhattan,New Lots,0,0,0,NaN,POINT (-73.908946 40.662549)

In [34]:
# Valores únicos en la columna de referencia (DF2)
referencia = set(df['stop_id'].str[:3])

# Valores en DF1 que son NaN o que simplemente no están en la referencia
faltantes_en_df2 = df2[~df2['GTFS Stop ID'].isin(referencia)]

print(f"Total de registros en DF2 sin coincidencia en DF1: {len(faltantes_en_df2)}")

Total de registros en DF2 sin coincidencia en DF1: 0

In [39]:
# Identifica cuáles son los IDs que sobran en tu dataset de entrenamiento
ids_entrenamiento = set(df['stop_id'].str[:3].unique())
ids_catalogo = set(df2['GTFS Stop ID'].str[:3].unique())

sobrantes_en_entrenamiento = ids_entrenamiento - ids_catalogo

print(f"IDs en el tráfico que NO están en el catálogo: {sobrantes_en_entrenamiento}")

IDs en el tráfico que NO están en el catálogo: {'S0L', 'B24', 'F10', 'F17', 'S10', 'D23', 'A62', 'S12', 'X22', 'H05', 'J18', 'A58', 'R60', 'A39', 'N12', 'H17', 'R10', 'B05', 'R70', 'R65', 'M07', 'H19', 'A29', 'D60', 'H18', 'G25', 'M17'}

In [40]:
for parada in sobrantes_en_entrenamiento:
    print(f"Parada: {parada}")
    print(df['stop_id'].str[:3].value_counts()[parada])

Parada: S0L
1
Parada: B24
206
Parada: F10
110
Parada: F17
134
Parada: S10
4
Parada: D23
348
Parada: A62
1451
Parada: S12
4
Parada: X22
2226
Parada: H05
102
Parada: J18
63
Parada: A58
1009
Parada: R60
17365
Parada: A39
257
Parada: N12
186
Parada: H17
94
Parada: R10
97
Parada: B05
134
Parada: R70
94
Parada: R65
7966
Parada: M07
183
Parada: H19
2644
Parada: A29
257
Parada: D60
694
Parada: H18
94
Parada: G25
138
Parada: M17
408

In [ ]:
df3 = pd.read_csv("MTA_Subway_Stations_and_Complexes_20260316.csv")

In [43]:
df3

,Complex ID,Is Complex,Number Of Stations In Complex,Stop Name,Display Name,Constituent Station Names,Station IDs,GTFS Stop IDs,Borough,CBD,Daytime Routes,Structure Type,Latitude,Longitude,ADA,ADA Notes
0,398,False,1,77 St,77 St (6),77 St,398,627,M,False,6,Subway,40.773620,-73.959874,0,NaN
1,399,False,1,68 St-Hunter College,68 St-Hunter College (6),68 St-Hunter College,399,628,M,False,6,Subway,40.768141,-73.963870,1,NaN
2,403,False,1,33 St,33 St (6),33 St,403,632,M,True,6,Subway,40.746081,-73.982076,0,NaN
3,404,False,1,28 St,28 St (6),28 St,404,633,M,True,6,Subway,40.743070,-73.984264,2,Downtown only
4,405,False,1,23 St-Baruch College,23 St-Baruch College (6),23 St-Baruch College,405,634,M,True,6,Subway,40.739864,-73.986599,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,134,False,1,Sutter Av,Sutter Av (L),Sutter Av,134,L25,Bk,False,L,Elevated,40.669367,-73.901975,0,NaN
441,135,False,1,Livonia Av,Livonia Av (L),Livonia Av,135,L26,Bk,False,L,Elevated,40.664038,-73.900571,1,NaN
442,136,False,1,New Lots Av,New Lots Av (L),New Lots Av,136,L27,Bk,False,L,Elevated,40.658733,-73.899232,0,NaN
443,137,False,1,East 105 St,East 105 St (L),East 105 St,137,L28,Bk,False,L,At Grade,40.650573,-73.899485,0,NaN
444,138,False,1,Canarsie-Rockaway Pkwy,Canarsie-Rockaway Pkwy (L),Canarsie-Rockaway Pkwy,138,L29,Bk,False,L,At Grade,40.646654,-73.901850,1,NaN

In [49]:
df3['GTFS Stop IDs'].value_counts()

GTFS Stop IDs
L29    1
627    1
628    1
632    1
633    1
      ..
211    1
210    1
209    1
208    1
207    1
Name: count, Length: 445, dtype: int64